# -*- coding: utf-8 -*-
"""dayonesci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1et__a4EFSZ_GskA-TW_vBK-f8w74Ok7L

DAY ONE
"""

import pandas as pd
df = pd.DataFrame({
    'name':['Asha','ravi','neha','kiran'],
    'Age' :[22,25,28,30],
    'Marks':[80,85,90,88]
},index =[1,2,3,4])

df

data = {
    'Name':['alice','bob','charlie'],
    'Age':[25,30,35],
    'salary':[50000,60000, 70000],
    'Department':['IT','HR','IT']
}
df = pd.DataFrame(data)
print(df)

df=pd.read_csv("/content/sales_data_sample.csv",encoding='latin1')

df

df.head()

df.tail()

df.info()

df.shape

df.columns

df.describe()

df.isnull()

df.isnull().sum()

df.duplicated()

data=pd.read_csv("/content/College.csv")

data

data.head()

data.tail()

data.info()

data.shape

data.describe()

data.columns

data.isnull()

data.isnull().sum()

data.duplicated()

df['COUNTRY']

df[['POSTALCODE','COUNTRY']]

df[['COUNTRY','STATE']]

df[['TERRITORY','STATE','ORDERNUMBER']]

df['CITY']

df[20:]

df[20:25]

df['COUNTRY'].value_counts()

df['COUNTRY'].unique()

df['COUNTRY'].nunique()

df['CITY'].value_counts()

df['CITY'].unique()

df['CITY'].nunique()

df.loc[0]

df.loc[25,'ORDERDATE']

df.loc[0:25,['ORDERDATE','COUNTRY']]

df.iloc[0:50,2]

df.iloc[10:23,4]

df.iloc[0:30,[0,3,2]]

df.iloc[0:23,[14,17,20]]

df.drop_duplicates(inplace=True)

df.rename(columns={'STATE':'STATE_NAME'},inplace=True)

df.rename(columns={'CITY':'REGION'},inplace=True)

df['ORDERDATE']

df['ORDERDATE']=pd.to_datetime(df['ORDERDATE'])

df['ORDERDATE']

df['year']=df['ORDERDATE'].dt.year
df['year']

df['month']=df['ORDERDATE'].dt.month
df['month']

df['day']=df['ORDERDATE'].dt.day
df['day']

df['PROFIT_EST']=df['SALES' ]* 0.2

df['PROFIT_EST']

df.drop('PROFIT_EST',axis=1,inplace=True)

df['FULLNAME'] = df['CONTACTFIRSTNAME']+''+df['CONTACTLASTNAME']

df['FULLNAME']

monthly_sales=df.groupby('MONTH_ID')['SALES'].sum()

monthly_sales
monthly_sales.plot(kind='line')

monthly_sales.plot(kind='pie')

df.groupby('COUNTRY')['SALES'].sum()

orders_per_year=df.groupby('YEAR_ID')['ORDERNUMBER'].nunique()

print(orders_per_year)

avg_sales_product = df.groupby('PRODUCTCODE')['SALES'].mean()
print(avg_sales_product)

df['DEALSIZE']

df['DEALSIZE'] = df['DEALSIZE'].str.upper()
df['DEALSIZE']

df.to_csv('cleaned_data.csv',index=False)

import pandas as pd
dd = pd.read_csv("/content/Zudio_sales_data.csv")

dd.head()

dd.tail()

dd.info()

dd.shape

dd.columns

dd.describe()

dd.isnull()

dd.isnull().sum()

dd.duplicated()

dd['Country']

dd[['Country','City']]

dd['Country'].value_counts()

dd['City'].unique()

dd['City'].nunique()

dd.loc[0]

dd.iloc[0:40,4]

dd.iloc[0:40,[0,2,1]]

dd.drop_duplicates(inplace=True)

dd['Order Date']=pd.to_datetime(dd['Order Date'])

dd['Order Date']

dd['day']=dd['Order Date'].dt.day
dd['day']

dd.rename(columns={'Sales Profit':'Sales'},inplace=True)

dd['Sales']

monthly_orders=dd.groupby('Month')['Price'].sum()
print(monthly_orders)

monthly_orders.plot(kind='line')

monthly_orders.plot(kind='bar')

dd.columns

dd.rename(columns={'Staff Count':'Count'})

dd['COST'] = dd['Price'] - 5
dd['COST']

avg_sales_profit = dd.groupby('Order ID')['Sales Profit'].mean().sort_values(ascending=False)
print(avg_sales_profit)

dd['Parking Availability']

dd['Parking Availability'] = dd['Parking Availability'].str.upper()
dd['Parking Availability']

dd.to_csv('Zudio_cleaned_data.csv',index=False)

